name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]     
        
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
#  Unit-test:
#    name: Run unit tests on PR in main
#    runs-on: ubuntu-20.04
#
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#      - name: Run unit tests
#        run: ./gradlew testDebugUnitTest